import React from 'react';
import '../Page.css';
import { GitHubIcon } from '../../components/Icons';

const ConversationAnalysis = () => {
    return (
        <div className="page">
            <header className="page-header">
                <h1>Chat Universe</h1>
            </header>
            <section>
                <div className="project-links">
                    <a href="https://github.com/gnahuy123/Conversation-Analysis" target="_blank" rel="noopener noreferrer" className="project-link-btn">
                        <GitHubIcon width="20" height="20" />
                        GitHub
                    </a>
                </div>

                <div className="project-content">
                    <p>
                        Chat Universe transforms Telegram chat exports into an analysed, searchable archive with
                        AI-powered memory capabilities. It surfaces patterns in conversations that would otherwise
                        be lost in thousands of messages — from emotional sentiment trends to automatically
                        generated yearly narratives.
                    </p>

                    <h3>Features</h3>
                    <ul>
                        <li><strong>Analytics Dashboard:</strong> Tracks message volume, response patterns, and emotional sentiment over time</li>
                        <li><strong>Semantic Search (RAG):</strong> Query past conversations using natural language via ChromaDB vector storage</li>
                        <li><strong>Automated Summaries:</strong> Monthly and yearly narrative summaries generated by Google Gemini</li>
                        <li><strong>Structured Data Extraction:</strong> Identifies nicknames, significant moments, and inside jokes in a queryable SQLite database</li>
                        <li><strong>Interactive UI:</strong> Streamlit-based dashboard with Plotly visualisations and word clouds</li>
                    </ul>

                    <h3>Tech Stack</h3>
                    <div className="tech-stack">
                        {['Python', 'Streamlit', 'Google Gemini', 'ChromaDB', 'SQLite', 'Plotly', 'SentenceTransformers', 'VADER'].map((tech, i) => (
                            <span key={i} className="tech-badge">{tech}</span>
                        ))}
                    </div>

                    <h3>Pipeline</h3>
                    <ul>
                        <li>Parse HTML chat exports from Telegram</li>
                        <li>Generate analytics and sentiment scores with VADER</li>
                        <li>Index messages semantically using SentenceTransformers embeddings</li>
                        <li>Precompute relationship summaries via Gemini API</li>
                        <li>Launch the interactive dashboard with <code>streamlit run app.py</code></li>
                    </ul>

                    <h3>Learning Points</h3>
                    <ul>
                        <li><strong>RAG Architecture:</strong> Implemented a full retrieval-augmented generation pipeline — from chunking and embedding messages to semantic querying with ChromaDB.</li>
                        <li><strong>LLM Integration:</strong> Worked with the Google Gemini API to generate coherent, context-aware narrative summaries from raw chat logs.</li>
                        <li><strong>Sentiment Analysis:</strong> Applied VADER to detect nuanced emotional tone across thousands of messages and surface trends over time.</li>
                        <li><strong>Data Engineering:</strong> Designed a multi-format storage strategy combining vector DB, SQLite, and flat files for different access patterns.</li>
                    </ul>
                </div>
            </section>
        </div>
    );
};

export default ConversationAnalysis;
